### ISSUE TITLE
Cachear la instalación de https

### ISSUE THREAD

**Issue by JJ** [JJ/plantilla-IV#23]
Usando esto, por ejemplo

```
- uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dia doxygen doxygen-doc doxygen-gui doxygen-latex graphviz mscgen
          version: 1.0
```
